baseurl = "https://corinnechin.video"
title = "Corinne Chin | Video Journalist"
languageCode = "en-us"
pygmentsUseClasses = false
PygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
cononifyurls = true
googleAnalytics = "UA-98836806-1"


[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Corinne Chin is an Emmy Award winning video journalist, trauma-informed safety trainer and leader in diversity, equity, belonging and inclusion."
  author = "Corinne Chin"
  favicon = "favicon.png"
