baseurl = "https://corinnechin.video"
title = "Corinne Chin | Video Journalist"
languageCode = "en-us"
pygmentsUseClasses = false
PygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
builddrafts = false
canonifyURLs = true
googleAnalytics = "UA-98836806-1"


[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Corinne Chin is an Emmy Award winning video journalist, trauma-informed safety trainer and leader in diversity, equity, belonging and inclusion."
  author = "Corinne Chin"
  favicon = "favicon.png"
