baseurl = "http://corinnechin.video"
title = "Corinne Chin | Video Journalist"
languageCode = "en-us"
pygmentsUseClasses = false
PygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
cononifyurls = true
googleAnalytics = "UA-98836806-1"


[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Corinne Chin is a video editor at The Seattle Times, where she works with a dynamic photo staff to film and edit short documentary films and compelling visual stories."
  author = "Corinne Chin"
  favicon = "favicon.png"

[params.social]
  twitter = "https://twitter.com/corinnechin"
  instagram = "https://instagram.com/corinnechinstagram"
  linkedin = "https://linkedin.com/in/corinnechin"
